import os
import uuid
from PIL import Image as PILImage
from google.genai import types
from loguru import logger
from app.config import TEMP_DIR

def clean_page_content(client, local_path: str, mask_path: str, filename: str) -> str:
    """
    Executes the Inpainting workflow using Google GenAI (Imagen 3).
    1. Prepares Reference Images (Raw + Mask).
    2. Calls EditImage Model.
    3. Composites the result over the original image strictly within the mask.
    
    Returns:
        clean_name (str): The filename of the cleaned image saved in TEMP_DIR.
    """
    if not client: 
        raise Exception("GenAI Client not initialized")

    try:
        # 1. Prepare References
        raw_ref = types.RawReferenceImage(
            reference_id=1, 
            reference_image=types.Image.from_file(location=local_path)
        )
        mask_ref = types.MaskReferenceImage(
            reference_id=2, 
            reference_image=types.Image.from_file(location=mask_path), 
            config=types.MaskReferenceConfig(mask_mode='MASK_MODE_USER_PROVIDED')
        )
        
        # 2. Call AI Model
        logger.info("🎨 Calling Imagen 3 for Inpainting...")
        resp = client.models.edit_image(
            model='imagen-3.0-capability-001',
            prompt="Remove text bubbles. Fill with background texture. Maintain art style.",
            reference_images=[raw_ref, mask_ref],
            config=types.EditImageConfig(
                edit_mode='EDIT_MODE_INPAINT_INSERTION', 
                number_of_images=1, 
                guidance_scale=60.0, 
                output_mime_type='image/png', 
                negative_prompt="text, bubbles, artifacts"
            )
        )
        
        session_id = uuid.uuid4().hex[:6]
        temp_ai_path = os.path.join(TEMP_DIR, f"temp_ai_{session_id}.png")
        
        if resp.generated_images: 
            resp.generated_images[0].image.save(temp_ai_path)
        else: 
            raise Exception("No image generated by AI")
        
        # 3. Compositing
        logger.info("🖼️ Compositing AI result with Original...")
        with PILImage.open(local_path) as orig, PILImage.open(temp_ai_path) as ai, PILImage.open(mask_path) as m:
            if ai.size != orig.size: 
                ai = ai.resize(orig.size, PILImage.LANCZOS)
            
            # Paste AI result ONLY where mask is white
            orig.paste(ai, (0,0), m.convert("L"))
            
            # FIX: Use session_id to prevent filename collisions across projects
            base_name, ext = os.path.splitext(filename)
            clean_name = f"clean_{session_id}_{base_name}{ext}"
            clean_path = os.path.join(TEMP_DIR, clean_name)
            orig.save(clean_path, quality=95)
        
        # Cleanup temp AI file
        try: os.remove(temp_ai_path)
        except: pass
        
        return clean_name

    except Exception as e:
        logger.error(f"❌ Inpainting Service Error: {e}")
        raise e
